title: San Diego Real Estate Video Blog
description: >-
  This is where you put a short description of your website, between 150-160
  characters.
keywords: keyword1, keyword2, keyword3
share_image: /uploads/logo.jpg
nav_USP_statement:
  text:
hero:
  hero_image: /img/gray.png
  use_overlay: true
  overlay-intensity: 0.5
  header: San Diego Real Estate Video Blog
  header_color: '#ffffff'
  subheader: >-
    A Veteran Owned Real Estate Company. Active Duty, Veteran And Civilian
    Staffed
  subheader_color: '#ffffff'
  button_text: Work With Tidal Realty
  button_link: https://www.authorized.company/team/tidal-realty
5star_review_excerpts:
  - text: Extremely RELIABLE, QUICK to respond, and THOROUGH.
  - text: Always available and answered all of our questions.
  - text: They worked tirelessly and were extremely RESULTS oriented.
  - text: Exceptional at finding properties which met our criteria.
sidebar_CTAs:
  - title: What's Your San Diego Home Worth?
    image: /uploads/pexels-luis-yanez-206172.jpg
    text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    button-text: Free Home Value Report
    url: https://www.authorized.company/campaign/tidal-realty-home-worth
  - title: Looking for a San DiegoHome?
    image: /uploads/pexels-mark-mccammon-2724749.jpg
    text: Search the entire MLS for your San Diego home.
    button-text: Search the MLS
    url: https://www.authorized.company/team-properties/tidal-realty
CTAS:
  - title: YouTube Channel
    url: https://www.google.com
  - title: About Us
    url: https://www.authorized.company/team-users/tidal-realty
  - title: Reviews
    url: https://www.zillow.com/profile/Tidal%20Realty
client:
  name: Claude Blackman
  brand:
  market: San Diego
  address: 411 Camino del Rio S STE 300
  city: San Diego
  state: California
  zip: 92108
  phone: (619) 473-4944
  email: claude@tidalre.com
  url: https://tidalre.com/
blog:
  CTA_main_box_markdown: >
    **Primary Call to Action Here.** There is where you can explain your primary
    call to action again so they see it when the website loads on mobile.
  CTA_main_box_link:
    title: Click Call To Action
    url: https://www.google.com
  author:
    name: John Doe
    name_link: mailto:johndoe@test.com
    image: /img/john-doe.png
    bio: >-
      This is where you have 1-2 sentences to explain why someone should listen
      to you.
  CTA_content_box:
    title_markdown: |
      **Want to work with us?** Here are some ways to get involved.
    items:
      - url: https://www.google.com
        markdown: >
          **Call to Action #1** is where you can explain what someone will get
          when they click the call to action button.
      - url: https://www.google.com
        markdown: >
          **Call to Action #2** is where you can explain what someone will get
          when they click the call to action button.
      - url: https://www.google.com
        markdown: >
          **Call to Action #3** is where you can explain what someone will get
          when they click the call to action button.
about:
  background_color: '#000000'
  headline: Why Hire Us Headline
  subheadline: Explain what you do in 1 short sentence
  youtube_code: NpEaa2P7qZI
  markdown: >-
    Do you have this specific problem? Are you struggling to find a solution to
    your pain? Well, you're not alone - 57% of people in your situation feel the
    same way. In fact, you can expect a lot of bad things to happen to you if
    you don't solve this problem. You may find yourself dealing with this bad
    thing or that bad thing. I've heard stories even that this terrible,
    terrible thing has happened when the problem does not go unsolved. My name
    is Bob and I'm here to help you solve this problem. This is what makes my
    solution different from everyone else's. I have a story here where I can
    relate to your situation and it's why I do what I do. Here is a list of the
    specific things we'll do for you:


    1. Killer benefit goes here.

    2. Killer benefit goes here.

    3. Killer benefit goes here.

    4. Killer benefit goes here.

    5. Killer benefit goes here.


    The whole goal is for you to live a happier and easier life with less stress
    and hassle and without any worries. Those are the benefits. But don't take
    my word for it - we have several happy customers who have the same problem
    you may have who hired us to solve and can vouch for our systems. In fact,
    we even offer a 100% money-back guarantee to remove all the risk - you won't
    lose any money. I invite you to take **Call to Action \#3** to learn more,
    **call to action \#2** to really go deeper, or **Call to action \#1** to get
    started on the solution to your problem.&nbsp;
testimonials:
  font_color: '#000000'
  quotes:
    - markdown_quote: >
        ### "You'll put a client testimonial here of one of your best customers
        that shares the problem they had before they hired you **and the
        benefits of you solving it."**
      name: John Doe
      image: /img/16x9-placeholder.png
      image_link: https://www.google.com
    - markdown_quote: >
        ### "You'll put a client testimonial here of one of your best customers
        that shares the problem they had before they hired you **and the
        benefits of you solving it."**
      name: John Doe
      image: /img/16x9-placeholder.png
      image_link: https://www.google.com
    - markdown_quote: >
        ### "You'll put a client testimonial here of one of your best customers
        that shares the problem they had before they hired you **and the
        benefits of you solving it."**
      name: John Doe
      image: /img/16x9-placeholder.png
      image_link: https://www.google.com
benefits_section:
  header: Main Benefit Statement Goes Here
  subheader: Repeat what makes you unique to customers here in this subheadline
  benefit_1: A top benefit of your service goes here
  benefit_2: A top benefit of your service goes here
  benefit_3: A top benefit of your service goes here
  benefit_4: A top benefit of your service goes here
  icon_image: /img/checkmark.png
  svg_icon_color: gray
podcast:
  title: '-- market -- Real Estate Podcast with -- client name --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- market
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- client brand -- - your professional
    -- market -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- market --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- client name --'
images:
  hero_dark_logo_path: /img/logo-dark.png
  hero_light_logo_path: /img/logo-light.png
  logo_width_number: 40
  post_cover: /img/cover.jpg
  sidenav-logo-width: 200
  footer-logo-width: 250
site_colors:
  brand_color: '#001e42'
  theme_color: '#999999'
  theme_text_color: '#000000'
  main_body_color: '#ffffff'
  main_body_text_color: '#212121'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#74bf44'
  button_text_color: '#ffffff'
  button_hover_border_color: '#e0e0e0'
  button_hover_background_color: '#333333'
  button_hover_text_color: '#e0e0e0'
  light_button_border_color: '#000000'
  light_button_background_color: '#ffffff'
  light_button_text_color: '#000000'
  light_button_hover_border_color: '#000000'
  light_button_hover_background_color: '#e0e0e0'
  light_button_hover_text_color: '#000000'
  transition: all 0.3s ease
OG:
  fb-admins: test-fb-admins
footer:
  font_color: '#ffffff'
  socials:
    - icon: /img/icons/youtube.png
      url: https://www.youtube.com/
    - icon: /img/icons/facebook.png
      url: https://www.facebook.com/TidalRealtySanDiego
    - icon: /img/icons/linkedin.png
      url: https://www.linkedin.com/company/tidal-realty/
    - icon: /img/icons/instagram.png
      url: https://www.instagram.com/tidalrealtysandiego/
    - icon: /img/icons/tiktok.png
      url: https://www.tiktok.com/
    - icon: /img/icons/twitter.png
      url:
    - icon: /img/icons/pinterest.png
      url:
    - icon: /img/icons/gmb.png
      url: https://www.google.com/business
    - icon: /img/icons/whatsapp.png
      url:
  policies:
    - title: Privacy Policy
      url: /test-url
    - title: Terms of Use
      url: /test-url
bottom_mobile_cta:
  cta_1_text: 'Call to Action #1'
  cta_1_link: https://www.google.com
  cta_2_text: 'Call to Action #2'
  cta_2_link: https://www.google.com
